version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14



  pre_build:
    commands:
      - echo Installing dependencies
      - npm install --global npm

  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: src

