version: 0.2

phases:
  install:
    commands:
#      installing node.js
      - echo Installing Node.js..
      - curl -fsSL https://deb.nodesource.com/setup_16.x |  bash -
      - apt-get install -y nodejs



  pre_build:
    commands:
      - echo Installing dependencies
      - npm install --global npm

  build:
    commands:
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build

